version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
              perl ci-config-rebuild.pl < .circleci/config.tmpl.yml > .circleci/build-all.yml
              cp -p .circleci/build-all.yml /tmp/
      - store-artifacts:
          name: Save generated configuration to artifacts
          path: /tmp/build-all.yml
      - continuation/continue:
          configuration_path: .circleci/build-all.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    when:
      and:
        - equal [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal [ "rhel9-build", << pipeline.schedule.name >> ]
    jobs:
      - setup
